--- TABLE: Departamentos
INSERT INTO departamentos(nombre,codigo) VALUES('Amazonas','01');
INSERT INTO departamentos(nombre,codigo) VALUES('Ancash','02');
INSERT INTO departamentos(nombre,codigo) VALUES('Apurimac','03');
INSERT INTO departamentos(nombre,codigo) VALUES('Arequipa','04');
INSERT INTO departamentos(nombre,codigo) VALUES('Ayacucho','05');
INSERT INTO departamentos(nombre,codigo) VALUES('Cajamarca','06');
INSERT INTO departamentos(nombre,codigo) VALUES('Callao','07');
INSERT INTO departamentos(nombre,codigo) VALUES('Cusco','08');
INSERT INTO departamentos(nombre,codigo) VALUES('Huancavelica','09');
INSERT INTO departamentos(nombre,codigo) VALUES('Huanuco','10');
INSERT INTO departamentos(nombre,codigo) VALUES('Ica','11');
INSERT INTO departamentos(nombre,codigo) VALUES('Junin','12');
INSERT INTO departamentos(nombre,codigo) VALUES('La Libertad','13');
INSERT INTO departamentos(nombre,codigo) VALUES('Lambayeque','14');
INSERT INTO departamentos(nombre,codigo) VALUES('Lima','15');
INSERT INTO departamentos(nombre,codigo) VALUES('Loreto','16');
INSERT INTO departamentos(nombre,codigo) VALUES('Madre de Dios','17');
INSERT INTO departamentos(nombre,codigo) VALUES('Moquegua','18');
INSERT INTO departamentos(nombre,codigo) VALUES('Pasco','19');
INSERT INTO departamentos(nombre,codigo) VALUES('Piura','20');
INSERT INTO departamentos(nombre,codigo) VALUES('Puno','21');
INSERT INTO departamentos(nombre,codigo) VALUES('San Martin','22');
INSERT INTO departamentos(nombre,codigo) VALUES('Tacna','23');
INSERT INTO departamentos(nombre,codigo) VALUES('Tumbes','24');
INSERT INTO departamentos(nombre,codigo) VALUES('Ucayali','25');
--- TABLE: Provincias
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,1,'Chachapoyas','0101');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,1,'Bagua','0102');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,1,'Bongara','0103');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,1,'Condorcanqui','0104');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,1,'Luya','0105');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,1,'Rodriguez de Mendoza','0106');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,1,'Utcubamba','0107');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,2,'Huaraz','0201');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,2,'Aija','0202');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,2,'Antonio Raymondi','0203');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,2,'Asuncion','0204');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,2,'Bolognesi','0205');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,2,'Carhuaz','0206');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,2,'Carlos Fermin Fitzcarrald','0207');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,2,'Casma','0208');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,2,'Corongo','0209');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,2,'Huari','0210');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,2,'Huarmey','0211');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(12,2,'Huaylas','0212');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(13,2,'Mariscal Luzuriaga','0213');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(14,2,'Ocros','0214');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(15,2,'Pallasca','0215');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(16,2,'Pomabamba','0216');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(17,2,'Recuay','0217');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(18,2,'Santa','0218');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(19,2,'Sihuas','0219');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(20,2,'Yungay','0220');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,3,'Abancay','0301');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,3,'Andahuaylas','0302');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,3,'Antabamba','0303');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,3,'Aymaraes','0304');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,3,'Cotabambas','0305');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,3,'Chincheros','0306');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,3,'Grau','0307');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,4,'Arequipa','0401');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,4,'Camana','0402');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,4,'Caraveli','0403');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,4,'Castilla','0404');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,4,'Caylloma','0405');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,4,'Condesuyos','0406');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,4,'Islay','0407');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,4,'La Union','0408');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,5,'Huamanga','0501');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,5,'Cangallo','0502');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,5,'Huanca Sancos','0503');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,5,'Huanta','0504');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,5,'La Mar','0505');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,5,'Lucanas','0506');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,5,'Parinacochas','0507');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,5,'Paucar del Sara Sara','0508');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,5,'Sucre','0509');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,5,'Victor Fajardo','0510');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,5,'Vilcas Huaman','0511');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,6,'Cajamarca','0601');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,6,'Cajabamba','0602');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,6,'Celendin','0603');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,6,'Chota','0604');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,6,'Contumaza','0605');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,6,'Cutervo','0606');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,6,'Hualgayoc','0607');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,6,'Jaen','0608');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,6,'San Ignacio','0609');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,6,'San Marcos','0610');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,6,'San Miguel','0611');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(12,6,'San Pablo','0612');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(13,6,'Santa Cruz','0613');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,7,'Prov. Const. del Callao','0701');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,8,'Cusco','0801');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,8,'Acomayo','0802');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,8,'Anta','0803');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,8,'Calca','0804');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,8,'Canas','0805');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,8,'Canchis','0806');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,8,'Chumbivilcas','0807');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,8,'Espinar','0808');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,8,'La Convencion','0809');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,8,'Paruro','0810');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,8,'Paucartambo','0811');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(12,8,'Quispicanchi','0812');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(13,8,'Urubamba','0813');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,9,'Huancavelica','0901');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,9,'Acobamba','0902');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,9,'Angaraes','0903');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,9,'Castrovirreyna','0904');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,9,'Churcampa','0905');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,9,'Huaytara','0906');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,9,'Tayacaja','0907');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,10,'Huanuco','1001');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,10,'Ambo','1002');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,10,'Dos de Mayo','1003');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,10,'Huacaybamba','1004');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,10,'Huamalies','1005');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,10,'Leoncio Prado','1006');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,10,'Marañon','1007');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,10,'Pachitea','1008');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,10,'Puerto Inca','1009');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,10,'Lauricocha','1010');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,10,'Yarowilca','1011');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,11,'Ica','1101');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,11,'Chincha','1102');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,11,'Nazca','1103');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,11,'Palpa','1104');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,11,'Pisco','1105');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,12,'Huancayo','1201');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,12,'Concepcion','1202');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,12,'Chanchamayo','1203');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,12,'Jauja','1204');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,12,'Junin','1205');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,12,'Satipo','1206');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,12,'Tarma','1207');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,12,'Yauli','1208');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,12,'Chupaca','1209');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,13,'Trujillo','1301');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,13,'Ascope','1302');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,13,'Bolivar','1303');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,13,'Chepen','1304');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,13,'Julcan','1305');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,13,'Otuzco','1306');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,13,'Pacasmayo','1307');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,13,'Pataz','1308');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,13,'Sanchez Carrion','1309');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,13,'Santiago de Chuco','1310');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,13,'Gran Chimu','1311');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(12,13,'Viru','1312');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,14,'Chiclayo','1401');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,14,'Ferreñafe','1402');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,14,'Lambayeque','1403');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,15,'Lima','1501');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,15,'Barranca','1502');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,15,'Cajatambo','1503');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,15,'Canta','1504');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,15,'Cañete','1505');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,15,'Huaral','1506');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,15,'Huarochiri','1507');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,15,'Huaura','1508');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,15,'Oyon','1509');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,15,'Yauyos','1510');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,16,'Maynas','1601');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,16,'Alto Amazonas','1602');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,16,'Loreto','1603');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,16,'Mariscal Ramon Castilla','1604');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,16,'Requena','1605');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,16,'Ucayali','1606');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,16,'Datem del Marañón','1607');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,16,'Putumayo','1608');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,17,'Tambopata','1701');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,17,'Manu','1702');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,17,'Tahuamanu','1703');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,18,'Mariscal Nieto','1801');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,18,'General Sanchez Cerro','1802');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,18,'Ilo','1803');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,19,'Pasco','1901');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,19,'Daniel Alcides Carrion','1902');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,19,'Oxapampa','1903');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,20,'Piura','2001');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,20,'Ayabaca','2002');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,20,'Huancabamba','2003');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,20,'Morropon','2004');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,20,'Paita','2005');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,20,'Sullana','2006');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,20,'Talara','2007');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,20,'Sechura','2008');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,21,'Puno','2101');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,21,'Azangaro','2102');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,21,'Carabaya','2103');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,21,'Chucuito','2104');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,21,'El Collao','2105');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,21,'Huancane','2106');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,21,'Lampa','2107');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,21,'Melgar','2108');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,21,'Moho','2109');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,21,'San Antonio de Putina','2110');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(11,21,'San Roman','2111');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(12,21,'Sandia','2112');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(13,21,'Yunguyo','2113');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,22,'Moyobamba','2201');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,22,'Bellavista','2202');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,22,'El Dorado','2203');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,22,'Huallaga','2204');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(5,22,'Lamas','2205');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(6,22,'Mariscal Caceres','2206');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(7,22,'Picota','2207');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(8,22,'Rioja','2208');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(9,22,'San Martin','2209');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(10,22,'Tocache','2210');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,23,'Tacna','2301');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,23,'Candarave','2302');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,23,'Jorge Basadre','2303');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,23,'Tarata','2304');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,24,'Tumbes','2401');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,24,'Contralmirante Villar','2402');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,24,'Zarumilla','2403');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(1,25,'Coronel Portillo','2501');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(2,25,'Atalaya','2502');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(3,25,'Padre Abad','2503');
INSERT INTO provincias(id,id_departamento,nombre,codigo) values(4,25,'Purus','2504');