/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.developer.bryan.ubigeo.api;

import org.junit.Test;
import static org.junit.Assert.*;

public class JavaUbigeoApiTest {
    @Test public void testAppHasAGreeting() {
        JavaUbigeoApi classUnderTest = new JavaUbigeoApi();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
