/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.developer.bryan.ubigeo.api;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class JavaUbigeoApiTest {

    @Test
    void contextLoads() {

    }
}
